stages:
  preprocess:
    cmd: python preprocess.py
    deps:
      - preprocess.py
    outs:
      - data/processed/train.csv
      - data/processed/test.csv
      - data/raw/iris.csv

  train:
    cmd: python train.py
    deps:
      - train.py
      - data/processed/train.csv
      - data/processed/test.csv
    outs:
      - models/random_forest.pkl

  tune:
    cmd: python tune.py
    deps:
      - tune.py
      - data/processed/train.csv
      - data/processed/test.csv
    outs:
      - models/best_svm.pkl
